# -*- coding: utf-8 -*-
"""Encoder_Text_Numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hHiL5mcsaGvDT0T9K3pNO-XeRCvEm0qf
"""

import streamlit as st

def encode(text, shift):
    """Encodes text using Caesar cipher with the given shift (works for letters and numbers)"""
    result = ""
    for char in text:
        if char.isupper():
            # Shift uppercase letters
            result += chr((ord(char) + shift - 65) % 26 + 65)
        elif char.islower():
            # Shift lowercase letters
            result += chr((ord(char) + shift - 97) % 26 + 97)
        elif char.isdigit():
            # Shift numbers (0-9)
            result += str((int(char) + shift) % 10)
        else:
            # Leave other characters unchanged
            result += char
    return result

def decode(text, shift):
    """Decodes text using Caesar cipher with the given shift"""
    return encode(text, -shift)

# Streamlit UI
st.title("Caesar Cipher Encoder/Decoder")

input_text = st.text_area("Enter your text here:", height=150)
shift = st.slider("Shift amount", min_value=1, max_value=25, value=3)

col1, col2 = st.columns(2)

result = ""

with col1:
    if st.button("Encode"):
        result = encode(input_text, shift)

with col2:
    if st.button("Decode"):
        result = decode(input_text, shift)

if result:
    st.subheader("Result:")
    st.text_area("Output", value=result, height=150)